version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: go_api_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: go_api_db
      MYSQL_USER: api_user
      MYSQL_PASSWORD: Password123
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - go_api_network

volumes:
  mysql_data:

networks:
  go_api_network:
    driver: bridge